# Project: Flutter-base Taxi
# Purpose: Testing integration of Flutter & Google Maps
# Platforms:  Web, iOS and Android
# Authors: www.flutterbase.com

name: flutterbasetaxi
description: Flutterbase Demo Project - a simple Uber App clone.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: 
  provider: 
  cupertino_icons: 
  flutter_animarker: 
  google_maps_flutter_web: 
  google_maps_flutter: 
  google_polyline_algorithm: 
  geolocator: 
  flutter_svg: 
  flutter_rating_bar: 
  lottie: 
  shimmer: 
  google_maps_webservice:
    git:
      url: https://github.com/YakivGalkin/google_maps_webservice

  uuid: 

  touch_indicator: 
  url_launcher: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/markers/
    - assets/lottie/
